#!/bin/sh

DOT_DIRECTORY="${HOME}/.dotfiles"
DOT_TARBALL="https://github.com/tamamu/dotfiles/tarball/master"
REMOTE_URL="https://github.com/tamamu/dotfiles.git"

POWERLINE_DIRECTORY="${HOME}/powerline_fonts"
POWERLINE_URL="https://github.com/powerline/fonts.git"

PREZTO_URL="https://github.com/sorin-ionescu/prezto.git"
PREZTO_DIRECTORY="${HOME}/.zprezto"

TPM_URL="https://github.com/tmux-plugins/tpm.git"
TPM_DIRECTORY="${HOME}/.tmux/plugins/tpm"

usage() {
  name=`basename $0`
  cat <<EOF
Usage:
  $name [arguments] [command]
Commands:
  deploy
  initialize
Arguments:
  -f $(tput setaf 1)** warning **$(tput sgr0) Overwrite dotfiles.
  -h Print help (this message)
EOF
  exit 1
}

while getopts :f:h opt; do
  case ${opt} in
    f)
      OVERWRITE=true
      ;;
    h)
      usage
      ;;
    esac
  done
shift $((OPTIND - 1))

put_proc() {
  echo $(tput setaf 3)* $1...$(tput sgr0)
}

put_comp() {
  echo $(tput setaf 2)✔ $1$(tput sgr0)
}

put_fail() {
  echo $(tput setaf 1)✗ $1$(tput sgr0)
}

download() {
  if [ -n "${OVERWRITE}" -o ! -d ${DOT_DIRECTORY} ]; then
    put_proc "Download dotfiles"
    rm -rf ${DOT_DIRECTORY}
    git clone --recursive ${REMOTE_URL} ${DOT_DIRECTORY}
    if [ $? = 0 ]; then
      put_comp "Download dotfiles complete."
    else
      put_fail "Download dotfiles failed."
      return 1
    fi
  fi
}

link_files() {
  put_proc "Link base16-shell"
  ln -s -i $DOT_DIRECTORY/base16-shell $HOME/.config/base16-shell
  put_proc "Link neovim config"
  ln -s -i $DOT_DIRECTORY/nvim $HOME/.config/nvim
  put_proc "Link zshrc"
  ln -s -i $DOT_DIRECTORY/zshrc $HOME/.zshrc
  put_proc "Linx zpreztorc"
  ln -s -i $DOT_DIRECTORY/zpreztorc $HOME/.zpreztorc
  put_proc "Link tmux config"
  ln -s -i $DOT_DIRECTORY/tmux.conf $HOME/.tmux.conf
  mkdir -p $HOME/.tmux
  ln -s -i $DOT_DIRECTORY/*_tmux $HOME/.tmux/
  put_proc "Link latexmkrc"
  ln -s -i $DOT_DIRECTORY/latexmkrc $HOME/.latexmkrc
}

initialize() {
  if [ -n "${OVERWRITE}" -o ! -d ${POWERLINE_DIRECTORY} ]; then
    put_proc "Download Powerline fonts"
    rm -rf ${POWERLINE_DIRECTORY}
    git clone ${POWERLINE_URL} --depth=1 ${POWERLINE_DIRECTORY}
    if [ $? = 0 ]; then
      put_comp "Download Powerline fonts complete."
      put_proc "Install Powerline fonts"
      bash ${POWERLINE_DIRECTORY}/install.sh
      rm -rf ${POWERLINE_DIRECTORY}
      put_comp "Install Powerline fonts complete."
    else
      put_fail "Install Powerline fonts failed. Skip."
    fi
  fi

  if [ -n "${OVERWRITE}" -o ! -d ${PREZTO_DIRECTORY} ]; then
    put_proc "Download Prezto"
    rm -rf ${PREZTO_DIRECTORY}
    git clone --recursive ${PREZTO_URL} ${PREZTO_DIRECTORY}
    put_comp "Download Prezto complete."
  fi

  if [ -n "${OVERWRITE}" -o ! -d ${TPM_DIRECTORY} ]; then
    put_proc "Download Tmux Plugin Manager"
    rm -rf ${TPM_DIRECTORY}
    git clone --recursive ${TPM_URL} ${TPM_DIRECTORY}
    put_comp "Download Tmux Plugin Manager complete."
  fi

  put_proc "Change shell to zsh"
  [ ${SHELL} != "/bin/zsh" ] && chsh -s /bin/zsh
  put_comp "Initialize complete."
}

command=$1
[ $# -gt 0 ] && shift

case $command in
  deploy)
    link_files
    ;;
  init)
    download && initialize
    ;;
  *)
    usage
    ;;
esac


exit 0
