#!/bin/zsh

case ${OSTYPE} in
  darwin*)
    if sound_info=$(osascript -e 'get volume settings'); then
      test "$(echo $sound_info | awk '{print $8}')" = "muted:true" && mute=0
      vol=$(expr $(echo $sound_info | awk '{print $2}' | sed "s/[^0-9]//g") / 6)
    else
      mute=0
      vol=0
    fi
    ;;
  linux*)
    vol=$((8*$(pamixer --get-volume)/100))
    test $(pamixer --get-mute) = "true" && mute=0
    ;;
esac

if $mute; then
  str=""
  for ((i=0; i < $vol; i++)); do
    str="${str}■"
  done
  for ((i=$vol; i < 8; i++)); do
    str="${str} "
  done
  sound="#[bold][$str]#[default] "
else
  sound="#[bold][      mute      ]#[default] "
fi

echo $sound
